[project]
name = "py-simple-chat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.3",
    "flask-socketio>=5.6.1",
    "uv>=0.10.4",
]
